spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Local?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds : 86400


  jpa:
    open-in-view: true

    hibernate:
      ddl-auto: create

    show-sql: true
    properties:
      hibernate:
        format_sql: true


