version : '3.8'

services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30


    ports:
      - "3306:3306"

    environment:
      - MYSQL_DATABASE=Local
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
      - MYSQL_ROOT_PASSWORD=admin123
      - TZ=Asia/Seoul